[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "quantum_logical"
description = "logical state encodings for error-detection/correction of quantum states"
version = "0.1.0"
authors = [{ name = "Evan McKinney" }]
requires-python = ">=3.11, <3.13"
dependencies = [
    "tqdm",
    "numpy",
    "qiskit",
    "qutip",
    "scqubits",
    "weylchamber",
    "matplotlib",
    "LovelyPlots",
    "rustworkx",
    "qutip-qip>=0.4.1",
    "ipykernel>=7.1.0",
    "cirq>=1.6.1",
]

[project.optional-dependencies]
dev = ["ipykernel", "pre-commit", "pylatexenc", "ipywidgets"]
format = [
    "pre-commit",
    "black[jupyter]",
    "isort",
    "tomli",
    "pydocstyle",
    "ruff",
    "docformatter[tomli]",
]
test = ["pytest"]

[tool.ruff]
target-version = "py311"
line-length = 88
fix = true

[tool.ruff.lint]
# 2. Merge isort by adding "I" (Isort) to your selected rules
# You likely have others here (like "E", "F"), just add "I" to the list.
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.format]
# Ruff's formatter is designed to be a drop-in replacement for Black
# So no extra config is needed here to match Black's style.
quote-style = "double"
indent-style = "space"


[[tool.setuptools-rust.ext-modules]]
target = "quantum_logical._lib"
# ^-- The last part of the target name (e.g. "rust") should match lib.name in Cargo.toml,
#     but you can add a prefix to nest it inside of a parent Python package or namespace.
#     Note that lib.name may not be defined in the Cargo.toml, but you still
#     have to match the name of the function with the `#[pymodule]` attribute.
path = "rustlib/Cargo.toml"
# ^-- Default value for cargo's manifest (can be omitted)
#     Each manifest can have a single [lib] definition.
#     To specify multiple extension modules you can use different toml files (one each).
binding = "PyO3" # Default value, can be omitted
debug = false
# See reference for RustExtension in https://setuptools-rust.readthedocs.io/en/latest/reference.html
